name: FACT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - markdown=3.4.1
  - markupsafe=2.1.1
  - numpy=1.23.1
  - matplotlib=3.5.3
  - pandas=1.4.3
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.10.5
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - tabulate=0.8.10
  - torchinfo=1.7.0
  - torchmetrics=0.9.3
  - tqdm=4.64.0
  - pip:
    - folktables
